print('=== Desafio (Antecessor e Sucessor) ===')
n1 = int(input('Informe um número: '))
print(n1 - 1,',',n1,',',n1 + 1,'\n')
print(' Antecessor: {}\n Número: {}\n Sucessor: {}\n'.format(n1 - 1, n1, n1 + 1))
print('-'*16)
